#!/bin/sh

gtk_dir=`gtk-config --prefix`include/gtk/
for file in gtk*.adb; do

   c_file=`echo $file | sed -e 's/\.ad[sb]$/.h/' -e 's/[_-]//g'` 
   
   echo "Comparing $gtk_dir$c_file and $file"
   ./generate.pl -l $gtk_dir$c_file $file
   echo ""

done
