/*********************************************************************
 *               GtkAda - Ada95 binding for Gtk+/Gnome               *
 *                                                                   *
 *   Copyright (C) 1998-2000 E. Briot, J. Brobecker and A. Charlet   *
 *                Copyright (C) 2000-2013, AdaCore                   *
 *                                                                   *
 * This library is free software; you can redistribute it and/or     *
 * modify it under the terms of the GNU General Public               *
 * License as published by the Free Software Foundation; either      *
 * version 2 of the License, or (at your option) any later version.  *
 *                                                                   *
 * This library is distributed in the hope that it will be useful,   *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of    *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU *
 * General Public License for more details.                          *
 *                                                                   *
 * You should have received a copy of the GNU General Public         *
 * License along with this library; if not, write to the             *
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,      *
 * Boston, MA 02111-1307, USA.                                       *
 *                                                                   *
 * As a special exception, if other files instantiate generics from  *
 * this unit, or you link this unit with other files to produce an   *
 * executable, this  unit  does not  by itself cause  the resulting  *
 * executable to be covered by the GNU General Public License. This  *
 * exception does not however invalidate any other reasons why the   *
 * executable file  might be covered by the  GNU Public License.     *
 *********************************************************************

This file is automatically generated from the .gir files
*/
#include <gtk/gtk.h>

gfloat gtkada_GtkAspectFrame_get_xalign (GtkAspectFrame* self) {
    return self->xalign;
}

gfloat gtkada_GtkAspectFrame_get_yalign (GtkAspectFrame* self) {
    return self->yalign;
}

gfloat gtkada_GtkAspectFrame_get_ratio (GtkAspectFrame* self) {
    return self->ratio;
}

GtkAdjustment* gtkada_GtkProgress_get_adjustment (GtkProgress* self) {
    return self->adjustment;
}

guint gtkada_GtkProgress_get_activity_mode (GtkProgress* self) {
    return self->activity_mode;
}

gfloat gtkada_GtkAlignment_get_xalign (GtkAlignment* self) {
    return self->xalign;
}

gfloat gtkada_GtkAlignment_get_yalign (GtkAlignment* self) {
    return self->yalign;
}

gfloat gtkada_GtkAlignment_get_xscale (GtkAlignment* self) {
    return self->xscale;
}

gfloat gtkada_GtkAlignment_get_yscale (GtkAlignment* self) {
    return self->yscale;
}

GtkWidget* gtkada_GtkDialog_get_vbox (GtkDialog* self) {
    return self->vbox;
}

GSList* gtkada_GtkStatusbar_get_messages (GtkStatusbar* self) {
    return self->messages;
}

GtkWidget* gtkada_GtkCombo_get_entry (GtkCombo* self) {
    return self->entry;
}

void gtkada_GtkCombo_set_entry (GtkCombo* self, GtkWidget* val) {
    self->entry = val;
}

GtkWidget* gtkada_GtkCombo_get_list (GtkCombo* self) {
    return self->list;
}
