--  DO NOT EDIT THIS FILE.
--  It is generated automatically, by program c-posix.c
------------------------------------------------------------------------------
--                                                                          --
--   POSIX Ada95 Bindings for Protocol Independent Interfaces (P1003.5c)    --
--                                                                          --
--                         P O S I X . O P T I O N S                        --
--                                                                          --
--                                   S p e c                                --
--                                                                          --
--                                                                          --
--                                                                          --
--  This  file  is a component of  FLORIST,  an  Ada  application  program  --
--  interface for operating system services for use with the GNAT compiler  --
--  and the  Gnu  Ada  Runtime  Library (GNARL).   FLORIST  is intended to  --
--  conform to the IEEE POSIX Ada standards, 1003.5-1992 and 1003.5b-1993.  --
--  It also includes support for Draft 1 of IEEE Project 1003.5c.           --
--                                                                          --
--  This package specification contains some text extracted from  IEEE STD  --
--  1003.5: 1990, Information Technology -- POSIX Ada Language  Interfaces  --
--  Part 1: Binding  for  System Application Program Interface, as amended  --
--  by IEEE STD 1003.5b: 1996, Amendment 1: Realtime Extensions, copyright  --
--  1996 by the Institute of Electrical and Electronics Engineers, Inc.     --
--                                                                          --
--  The package specifications in the IEEE standards cited above represent  --
--  only a  portion  of  the  documents  and  are  not to be interpreteted  --
--  outside the context  of  the documents.  The standards must be used in  --
--  conjunction  with  the  package   specifications  in  order  to  claim  --
--  conformance.   The IEEE takes no responsibility for and will assume no  --
--  liability for damages resulting from the reader's misinterpretation of  --
--  said  information resulting from its out-of-context nature.   To order  --
--  copies of the IEEE standards,  please contact the  IEEE Service Center  --
--  at 445 Hoes Lane, PO Box 1331, Piscataway, NJ 08855-1331; via phone at  --
--  1-800-678-IEEE, 908-981-1393; or via fax at 908-981-9667.               --
--                                                                          --
--  These  package  specifications are  distributed in  the hope that they  --
--  will  be useful, but  WITHOUT  ANY  WARRANTY; without even the implied  --
--  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.        --
--                                                                          --
------------------------------------------------------------------------------
package POSIX.Options is
   subtype Asynchronous_IO_Support is Boolean range
      True .. True;
   subtype Change_Owner_Restriction is
      POSIX.Change_Owner_Restriction;
   subtype Filename_Truncation is
      POSIX.Filename_Truncation;
   subtype File_Synchronization_Support is Boolean range
      True .. True;
   subtype Job_Control_Support is
      POSIX.Job_Control_Support;
   subtype Memory_Mapped_Files_Support is Boolean range
      True .. True;
   subtype Memory_Locking_Support is Boolean range
      True .. True;
   subtype Memory_Range_Locking_Support is Boolean range
      True .. True;
   subtype Memory_Protection_Support is Boolean range
      True .. True;
   subtype Message_Queues_Support is Boolean range
      True .. True;
   subtype Saved_IDs_Support is
      POSIX.Saved_IDs_Support;
   subtype Mutexes_Support is Boolean range
      True .. True;
   subtype Prioritized_IO_Support is Boolean range
      True .. True;
   subtype Priority_Process_Scheduling_Support is Boolean range
      True .. True;
   subtype Priority_Task_Scheduling_Support is Boolean range
      True .. True;
   subtype Realtime_Signals_Support is Boolean range
      True .. True;
   subtype Semaphores_Support is Boolean range
      True .. True;
   subtype Shared_Memory_Objects_Support is Boolean range
      True .. True;
   subtype Signal_Entries_Support is Boolean range
      True .. True;
   subtype Synchronized_IO_Support is Boolean range
      True .. True;
   subtype Mutex_Priority_Ceiling_Support is Boolean range
      True .. True;
   subtype Mutex_Priority_Inheritance_Support is Boolean range
      True .. True;
   subtype Process_Shared_Support is Boolean range
      True .. True;
   subtype Timers_Support is Boolean range
      True .. True;
   subtype XTI_DNI_Support is Boolean range
      False .. True;
   subtype Internet_Datagram_Support is Boolean range
      False .. True;
   subtype Internet_Protocol_Support is Boolean range
      False .. True;
   subtype Internet_Stream_Support is Boolean range
      False .. True;
   subtype ISO_OSI_Protocol_Support is Boolean range
      False .. True;
   subtype OSI_Minimal_Support is Boolean range
      False .. True;
   subtype OSI_Connection_Support is Boolean range
      False .. True;
   subtype OSI_Connectionless_Support is Boolean range
      False .. True;
   subtype Poll_Support is Boolean range
      False .. True;
   subtype Select_Support is Boolean range
      False .. True;
   subtype Sockets_DNI_Support is Boolean range
      False .. True;
   subtype Network_Management_Support is Boolean range
      False .. True;
end POSIX.Options;
