all: force
	make -C gtkdial all
	make -C helloworld all
	make -C helloworld2 all
	make -C packbox all
	make -C simple all
	make -C table all
	make -C tictactoe all
clean: 
	make -C gtkdial clean
	make -C helloworld clean
	make -C helloworld2 clean
	make -C packbox clean
	make -C simple clean
	make -C table clean
	make -C tictactoe clean
force:
