                when 0 => (case Version.Service_Pack (2) is
                  when 'B' | 'C' => "Windows_1_4_B_System",
                  when others    => "Windows_1_4_A_System"),
                when 10 => (case Version.Service_Pack (2) is
                  when 'A'       => "Windows_1_4_10_B_System",
                  when others    => "Windows_1_4_10_A_System"),
                when 90          => "Windows_1_4_90_System",
                when others      => "Windows_1_4_System"),
              when others        => "Windows_1_System"),
            when 2 => (case Version.Major is
              when 5 => (case Version.Minor is
                when 1           => "Windows_2_5_1_System",
                when others      => "Windows_2_5_System"),
              when 6 => (case Version.Minor is
                when 1           => "Windows_2_6_1_System",
                when 2           => "Windows_2_6_2_System",
                when others      => "Windows_2_6_System"),
              when others        => "Windows_2_System"),
            when others          => "Windows_System"));